"""Application-wide constants and default settings."""

APP_NAME = "MeadowPy"
APP_ID = "meadowpy.ide.meadowpy"
VERSION = "1.1.5"
CONFIG_DIR_NAME = ".meadowpy"
SETTINGS_FILENAME = "settings.json"
RECENT_FILES_MAX = 15
UNTITLED_PREFIX = "Untitled"

# Generated by QMainWindow.saveState().toBase64() from the default
# beginner layout: editor centered, help/project panels on the right,
# and a full-width output panel at the bottom.
DEFAULT_WINDOW_LAYOUT_VERSION = 3
DEFAULT_WINDOW_STATE = "AAAA/wAAAAD9AAAAAgAAAAEAAAHyAAACWPwCAAAAA/wAAABIAAAA5wAAAMEBAAAf+gAAAAABAAAAA/sAAAAYAEYAaQBsAGUARQB4AHAAbABvAHIAZQByAQAAAAD/////AAAAjgD////7AAAAGgBQAHIAbwBiAGwAZQBtAHMAUABhAG4AZQBsAQAAAAD/////AAAAmgD////7AAAAGgBTAHkAbQBiAG8AbABPAHUAdABsAGkAbgBlAQAABQoAAAD2AAAASgD////8AAABMgAAAW4AAAEFAQAAH/oAAAAAAQAAAAL7AAAAFgBBAEkAQwBoAGEAdABQAGEAbgBlAGwBAAAErAAAAVQAAAE+AP////sAAAAWAFMAZQBhAHIAYwBoAFAAYQBuAGUAbAEAAAAA/////wAAAN8A/////AAAArAAAACxAAAAAAD////6/////wEAAAAD+wAAABQAVwBhAHQAYwBoAFAAYQBuAGUAbAAAAAAA/////wAAAG4A////+wAAABwAQwBhAGwAbABTAHQAYQBjAGsAUABhAG4AZQBsAAAAAAD/////AAAASAD////7AAAAIgBWAGEAcgBpAGEAYgBsAGUASQBuAHMAcABlAGMAdABvAHIAAAAAAP////8AAABIAP///wAAAAMAAAYAAAAAvvwBAAAAAfsAAAAWAE8AdQB0AHAAdQB0AFAAYQBuAGUAbAEAAAAAAAAGAAAAAOAA////AAAECwAAAlgAAAAEAAAABAAAAAgAAAAI/AAAAAEAAAACAAAAAQAAABYATQBhAGkAbgBUAG8AbwBsAEIAYQByAQAAAAD/////AAAAAAAAAAA="
LEGACY_DEFAULT_WINDOW_STATES = frozenset({
    "AAAA/wAAAAD9AAAAAgAAAAEAAAHyAAACN/wCAAAAA/wAAABIAAAA0AAAAMEBAAAf+gAAAAABAAAAA/sAAAAYAEYAaQBsAGUARQB4AHAAbABvAHIAZQByAQAAAAD/////AAAAjgD////7AAAAGgBQAHIAbwBiAGwAZQBtAHMAUABhAG4AZQBsAQAAAAD/////AAAASgD////7AAAAGgBTAHkAbQBiAG8AbABPAHUAdABsAGkAbgBlAQAABQoAAAD2AAAASgD////8AAABGwAAAWQAAAEFAQAAH/oAAAABAQAAAAL7AAAAFgBTAGUAYQByAGMAaABQAGEAbgBlAGwBAAAAAP////8AAADfAP////sAAAAWAEEASQBDAGgAYQB0AFAAYQBuAGUAbAEAAASsAAABVAAAAT4A/////AAAArAAAACxAAAAAAD////6/////wEAAAAD+wAAABQAVwBhAHQAYwBoAFAAYQBuAGUAbAAAAAAA/////wAAAG4A////+wAAABwAQwBhAGwAbABTAHQAYQBjAGsAUABhAG4AZQBsAAAAAAD/////AAAASAD////7AAAAIgBWAGEAcgBpAGEAYgBsAGUASQBuAHMAcABlAGMAdABvAHIAAAAAAP////8AAABIAP///wAAAAMAAAYAAAAA3/wBAAAAAfsAAAAWAE8AdQB0AHAAdQB0AFAAYQBuAGUAbAEAAAAAAAAGAAAAAOAA////AAAECwAAAjcAAAAEAAAABAAAAAgAAAAI/AAAAAEAAAACAAAAAQAAABYATQBhAGkAbgBUAG8AbwBsAEIAYQByAQAAAAD/////AAAAAAAAAAA=",
    "AAAA/wAAAAD9AAAAAgAAAAAAAAE9AAADGfwCAAAAAvsAAAAYAEYAaQBsAGUARQB4AHAAbABvAHIAZQByAQAAAEgAAAFyAAAAgwD////7AAAAFgBPAHUAdABwAHUAdABQAGEAbgBlAGwBAAABvQAAAaQAAACzAP///wAAAAEAAAEgAAADGfwCAAAAA/wAAABIAAABdwAAAIgBAAAi+gAAAAEBAAAAAvsAAAAaAFAAcgBvAGIAbABlAG0AcwBQAGEAbgBlAGwBAAAAAP////8AAABIAP////sAAAAaAFMAeQBtAGIAbwBsAE8AdQB0AGwAaQBuAGUBAAAFCgAAAPYAAABIAP////wAAAHCAAABnwAAAQoBAAAi+gAAAAABAAAAAvsAAAAWAEEASQBDAGgAYQB0AFAAYQBuAGUAbAEAAATgAAABIAAAAKgA////+wAAABYAUwBlAGEAcgBjAGgAUABhAG4AZQBsAQAAAAD/////AAAAzwD////8AAAAzgAAAK0AAAAAAP////r/////AQAAAAP7AAAAFABXAGEAdABjAGgAUABhAG4AZQBsAAAAAAD/////AAAAbgD////7AAAAHABDAGEAbABsAFMAdABhAGMAawBQAGEAbgBlAGwAAAAAAP////8AAABIAP////sAAAAiAFYAYQByAGkAYQBiAGwAZQBJAG4AcwBwAGUAYwB0AG8AcgAAAAAA/////wAAAEgA////AAADnQAAAxkAAAAEAAAABAAAAAgAAAAI/AAAAAEAAAACAAAAAQAAABYATQBhAGkAbgBUAG8AbwBsAEIAYQByAQAAAAD/////AAAAAAAAAAA=",
})

DEFAULT_SETTINGS = {
    "editor.font_family": "Consolas",
    "editor.font_size": 14,
    "editor.tab_width": 4,
    "editor.use_spaces": True,
    "editor.show_line_numbers": True,
    "editor.highlight_current_line": True,
    "editor.word_wrap": True,
    "editor.show_whitespace": False,
    "editor.show_indentation_guides": False,
    "editor.auto_indent": True,
    "editor.brace_matching": True,
    "editor.code_folding": True,
    "editor.theme": "default_dark",
    # When editor.theme == "custom", these determine the appearance:
    #   base   — which template to render ("light" or "dark")
    #   accent — the hex accent color that replaces the default green
    "editor.custom_theme.base": "dark",
    "editor.custom_theme.accent": "#3B82F6",
    "window.geometry": None,
    "window.state": DEFAULT_WINDOW_STATE,
    "window.layout_version": DEFAULT_WINDOW_LAYOUT_VERSION,
    "window.recent_files": [],
    # Phase 2: Code Intelligence
    "editor.smart_indent": True,
    "editor.auto_close_brackets": True,
    "editor.auto_complete": True,
    "editor.auto_complete_threshold": 2,
    "editor.show_symbol_outline": True,
    "editor.linting_enabled": True,
    "editor.linter": "flake8",
    "editor.lint_on_save": True,
    "editor.show_lint_style_issues": True,
    "editor.lint_delay_ms": 1500,

    # Phase 3: Code Execution
    "run.python_interpreter": "",           # empty = auto-detect (sys.executable)
    "run.working_directory": "file",        # "file" = file's parent dir
    "run.clear_output_before_run": True,
    "run.save_before_run": True,
    "run.max_output_lines": 10000,
    "run.show_output_panel": True,          # auto-show output panel on run

    "general.auto_save_interval": 0,
    "general.restore_tabs_on_startup": True,
    "general.open_files": [],

    # Phase 5: File Explorer
    "general.project_folder": "",
    "explorer.show_file_explorer": True,

    # Interactive Console (REPL)
    "repl.auto_start": True,

    # Phase 7: Ollama AI Integration
    "ollama.api_url": "http://localhost:11434",
    "ollama.selected_model": "",
    "ollama.auto_connect": True,
}
